using Printf
using Statistics

# Linear arrays
println("\nLinear arrays:")
f = Int64[1, 2, 3, 4, 5, 3, 4, 5, 6]
println(f)

# Autogenerated arrays
println("\nAutogenerated arrays:")
a = zeros(Int64, 3, 3)
println(a)

b = Array{Int64}(undef, 3, 3)
println(b)

c = ones(Int64, 3, 3)
println(c)

d = fill(97, 3, 3)
println(d)

# Random arrays
println("\nRandom arrays:")

e1 = rand(Int64, 3, 3)
println(e1)

e2 = rand(3, 3)
println(e2)

e3 = rand(1:10, 3, 3)
println(e3)

# Array of functions
println("\nArray of functions:")
functions = [sin, cos, tan]
for fun in functions
    println(fun(3.14))
end

# Generating arrays
f_sq = [i^2 for i in 1:10]
println("f_sq:\n$f_sq")

# Matrix traversal
println("\nMatrix creation:")
m = [1 2 3; 4 5 6; 7 8 9]
for i in 1:3, j in 1:3
    println(m[i, j])
end

# Matrix generation
println("\nMatrix generation:")
m = [i * j for i in 1:3, j in 1:3]
println("m:\n$m")

# Collecting arrays
println("\nCollecting arrays:")
s = collect(1:2:10)
println("s:\n$s")